name: test
on:
- pull_request
jobs:
  vapor_macos:
    runs-on: macos-10.15
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4_beta.app/Contents/Developer
    steps:
    - uses: actions/checkout@v2
    - run: brew install mozjpeg libressl pkg-config
    - run: make test

  vapor_xenial:
    container:
      image: swift:5.5.0-xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./install-linux-dependencies.sh
    - run: make test

  vapor_bionic:
    container:
      image: swift:5.5.0-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./install-linux-dependencies.sh
    - run: make test

  vapor_focal:
    container:
      image: swift:5.5.0-focal
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./install-linux-dependencies.sh
      - run: make test
